<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="53" started-at="2015-04-24T05:24:08Z" finished-at="2015-04-24T05:24:08Z">
    <groups>
    </groups>
    <test name="Service" duration-ms="20" started-at="2015-04-24T05:24:08Z" finished-at="2015-04-24T05:24:08Z">
      <class name="ServicesTest">
        <test-method status="PASS" signature="COMPARE_BY_DESC_TYPE_Test()" name="COMPARE_BY_DESC_TYPE_Test" duration-ms="10" started-at="2015-04-24T05:24:08Z" finished-at="2015-04-24T05:24:08Z">
        </test-method>
        <test-method status="FAIL" signature="readAllExceptionTest()" name="readAllExceptionTest" duration-ms="2" started-at="2015-04-24T05:24:08Z" finished-at="2015-04-24T05:24:08Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception java.lang.IndexOutOfBoundsException but got org.testng.TestException: 
Method ServicesTest.readAllExceptionTest() should have thrown an exception of class java.lang.IndexOutOfBoundsException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception java.lang.IndexOutOfBoundsException but got org.testng.TestException: 
Method ServicesTest.readAllExceptionTest() should have thrown an exception of class java.lang.IndexOutOfBoundsException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1184)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at TestRunner.main(TestRunner.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.testng.TestException: 
Method ServicesTest.readAllExceptionTest() should have thrown an exception of class java.lang.IndexOutOfBoundsException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1442)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:722)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	... 20 more
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="FAIL" signature="readAllTest()" name="readAllTest" duration-ms="0" started-at="2015-04-24T05:24:08Z" finished-at="2015-04-24T05:24:08Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at ServicesTest.readAllTest(ServicesTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at TestRunner.main(TestRunner.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
    <test name="FirstTest" duration-ms="0" started-at="2015-04-24T05:24:08Z" finished-at="2015-04-24T05:24:08Z">
    </test>
  </suite>
</testng-results>
